name: Update list of weather stations
on:
  workflow_dispatch:
jobs:
  scrape-stations:
    name: Scrape weather stations
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python 3.7"
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install GDAL
        run: sudo apt-get install gdal-bin
      - name: Run scraper
        run: |
          cp stations.csv stations-old.csv
          scrapy runspider weather_stations_iceland.py -O stations.csv
      - name: Convert stations CSV to GeoJSON
        run: |
          rm stations.geojson
          ogr2ogr stations.geojson stations.csv -oo X_POSSIBLE_NAMES=longitude -oo Y_POSSIBLE_NAMES=latitude -oo KEEP_GEOM_COLUMNS=NO
      - name: Commit changes
        run: |
          git add stations.csv
          git add stations.geojson
          git config --global user.email "matt.riggott@gmail.com"
          git config --global user.name "Matt Riggott"
          echo -e 'Update weather stations data\n\n' > message.txt
          csv-diff stations-old.csv stations.csv --key=station_number --singular=station --plural=stations >> message.txt
          git commit -F message.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
